#!/bin/bash

# Exit on any error
set -e

# set the root directory to the current directory
ROOT_DIR="$(pwd)"
SRC_DIR="$ROOT_DIR/src"
COMPILED_DIR="$ROOT_DIR/compiled"
CONFIG="$ROOT_DIR/config.json"

# Function to compile a specific service - generated by gemini
compile_service() {
    SERVICE_NAME=$1
    # Compiles all .java files in the service directory into the compiled folder
    # Includes Helpers.java in every compilation to ensure dependencies are met
    javac -d "$COMPILED_DIR" "$SRC_DIR/$SERVICE_NAME"/*.java "$SRC_DIR/Helpers/Helpers.java"
}

# Function to run a Java service - generated by gemini
run_service() {
    SERVICE_NAME=$1
    # Runs the class matching the package name from the compiled directory
    java -cp "$COMPILED_DIR" "$SERVICE_NAME.$SERVICE_NAME" "$CONFIG"
}
# if arguement 1 is -c (compile all services)
if [ "$1" == "-c" ]; then
    echo "=== Cleaning and Compiling All Services ==="
    rm -rf "$COMPILED_DIR"
    mkdir -p "$COMPILED_DIR"
    
    # Compile Helpers as they are the dependency for the other services
    javac -d "$COMPILED_DIR" "$SRC_DIR/Helpers/Helpers.java"
    
    compile_service "ISCS"
    compile_service "UserService"
    compile_service "ProductService"
    compile_service "OrderService"
    echo "Compilation Complete"

elif [ "$1" == "-u" ]; then
    run_service "UserService"

elif [ "$1" == "-p" ]; then
    run_service "ProductService"

elif [ "$1" == "-i" ]; then
    run_service "ISCS"

elif [ "$1" == "-o" ]; then
    run_service "OrderService"

elif [ "$1" == "-w" ]; then
    if [ -z "$2" ]; then
        echo "Error: Provide a workload file"
        exit 1
    fi
    # compile workload parser and run it
    javac -d "$COMPILED_DIR" "$SRC_DIR/OrderService/WorkloadParser.java" "$SRC_DIR/Helpers/Helpers.java"
    java -cp "$COMPILED_DIR" "OrderService.WorkloadParser" "$2"

else
    # print usage instructions - generated by gemini
    echo "Usage Instructions:"
    echo "  ./runme.sh -c                Compile all services"
    echo "  ./runme.sh -u                Start User Service"
    echo "  ./runme.sh -p                Start Product Service"
    echo "  ./runme.sh -i                Start ISCS (Router)"
    echo "  ./runme.sh -o                Start Order Service"
    echo "  ./runme.sh -w <file>         Run Workload Parser"
fi